core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path('', views.post_list, name='post-list'),
    path('create/', views.post_create, name='post-create'),
    path('<slug:slug>/', views.post_detail, name='post-detail'),
    path('<slug:slug>/update/', views.post_update, name='post-update'),
    path('<slug:slug>/delete/', views.post_delete, name='post-delete'),
    path('user/<str:username>/', views.user_post_list, name='user-post-list'),
    path('topic/<str:link>/', views.topic, name='topic'),
    path('search/', views.search, name='search'),
    path('profile/<str:username>/', views.public_profile, name='public-profile'),
    path('rate/<slug:slug>/<int:rating>/', views.rate_post_view, name='rate-post'),
    path('comment/<slug:slug>/', views.comment, name='comment'),
    path('contact/', views.contact_create, name='contact-create'),
    path('search-list/', views.post_search_list, name='search-list'),
]

subscription/urls.py
from django.urls import path
from . import views

app_name = "subscription"

urlpatterns = [
    path('subscriptions/', views.subscriptions_list, name='subscriptions_list'),
    path('subscription/<int:pk>/', views.subscription_detail, name='subscription_detail'),
    path('checkout/', views.checkout, name='checkout'),
    path('execute_payment/', views.execute_payment, name='execute_payment'),
    path('cancel_payment/', views.cancel_payment, name='cancel_payment'),
]

work_hub/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import notifications.urls

from django.views.generic.base import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    path('messages/', include('directmessages.urls')),
    path('subscription/', include('subscription.urls')),
    path('blogs/', include('core.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('sitemap_manager.urls')),
    path('jobs/', include('jobs.urls')),
    path('account/', include('users.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('social-auth/', include('social_django.urls', namespace="social")),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),name='password_reset_confirm'),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),name='password_reset_complete'),
    path(
        "robots.txt",
        TemplateView.as_view(template_name="core/robots.txt", content_type="text/plain"),
    ),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

subscription/models.py
from django.db import models
from django.contrib.auth.models import User

class Benefit(models.Model):
    """
    Benefit Model represents different benefits available for subscription plans.

    Attributes:
    - name: The name of the benefit.
    """
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Subscription(models.Model):
    """
    Subscription Model represents different subscription plans available.

    Attributes:
    - name: The name of the subscription plan.
    - price: The price of the subscription plan.
    - benefits: Many-to-Many relationship with Benefit model.
    - duration_in_days: Duration of the subscription plan in days.
    - is_active: Boolean field to indicate if the subscription is currently active.
    """
    name = models.CharField(max_length=100)
    price = models.FloatField()
    benefits = models.ManyToManyField(Benefit)
    duration_in_days = models.PositiveIntegerField(default=30)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.name} - ${self.price}"

class UserSubscription(models.Model):
    """
    UserSubscription Model links users to their chosen subscription plans.

    Attributes:
    - user: The user associated with the subscription.
    - subscription: The chosen subscription plan.
    - start_date: The start date of the subscription.
    - end_date: The end date of the subscription.
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    subscription = models.ForeignKey(Subscription, on_delete=models.CASCADE)
    start_date = models.DateField()
    end_date = models.DateField()

    def __str__(self):
        return f"{self.user.username} - {self.subscription.name}"

subscription/views.py
from datetime import datetime, timedelta
from django.utils import timezone
import paypalrestsdk
from paypalrestsdk import Payment
from django.urls import reverse
from django.conf import settings
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from .models import Subscription, UserSubscription
from django.contrib.auth.decorators import login_required

# Configure PayPal SDK
paypalrestsdk.configure({
    "mode": settings.PAYPAL_MODE,
    "client_id": settings.PAYPAL_CLIENT_ID,
    "client_secret": settings.PAYPAL_CLIENT_SECRET,
})

def subscriptions_list(request):
    """
    Render a list of subscriptions.

    Args:
    - request: HttpRequest object

    Returns:
    - HttpResponse object containing rendered HTML template
    """
    subscriptions = Subscription.objects.all()
    context = {
        'subscriptions': subscriptions
    }
    return render(request, 'subscription/subscriptions_list.html', context)

@login_required
def subscription_detail(request, pk):
    """
    Render details of a particular subscription.

    Args:
    - request: HttpRequest object
    - pk: Primary key of the subscription

    Returns:
    - HttpResponse object containing rendered HTML template
    """
    subscription = get_object_or_404(Subscription, pk=pk)

    monthly_price = round(subscription.price, 2)
    semi_annual_price = round(monthly_price * 6 * 0.8, 2)
    annual_price = round(monthly_price * 12 * 0.65, 2)
    context = {
        'subscription': subscription,
        'monthly_price': monthly_price,
        'semi_annual_price': semi_annual_price,
        'annual_price': annual_price,
    }
    return render(request, 'subscription/subscription_detail.html', context)

@login_required
def execute_payment(request):
    """
    Execute a payment for a user subscription.

    Args:
    - request: HttpRequest object

    Returns:
    - HttpResponse indicating the status of payment execution
    """
    if request.method == 'POST':
        payment_id = request.POST.get('payment_id')
        payer_id = request.POST.get('payer_id')
        subscription_id = request.POST.get('subscription_id')
        selected_price = request.POST.get('selected_price')

        user_subscription = get_object_or_404(UserSubscription, subscription_id=subscription_id, user=request.user)

        payment = Payment.find(payment_id)
        if payment.execute({"payer_id": payer_id}):
            user_subscription.is_paid = True
            user_subscription.save()
            return HttpResponse("Payment successful!")
        else:
            return HttpResponse("Payment execution failed.")
    else:
        return HttpResponse("Invalid request method")
    
@login_required
def cancel_payment(request):
    """
    Cancel the payment process and handle the necessary actions.

    Args:
    - request: HttpRequest object

    Returns:
    - HttpResponse object indicating the cancellation status
    """
    return HttpResponse("Payment has been canceled.")

@login_required
def checkout(request):
    """
    Handle the checkout process for subscribing to a plan.

    Args:
    - request: HttpRequest object

    Returns:
    - HttpResponse object containing rendered HTML template or redirection to PayPal
    """
    if request.method == 'POST':
        subscription_id = request.POST.get('subscription_id')
        selected_duration = request.POST.get('selected_duration')
        
        if selected_duration == 'monthly':
            selected_price = request.POST.get('monthly_price')
            duration_in_days = 31
        elif selected_duration == 'semi_annual':
            selected_price = request.POST.get('semi_annual_price')
            duration_in_days = 183
        elif selected_duration == 'annual':
            selected_price = request.POST.get('annual_price')
            duration_in_days = 366
        else:
            return HttpResponse("Invalid duration selection")

        start_date = datetime.now().date()
        end_date = start_date + timedelta(days=duration_in_days)
        
        user = request.user
        
        user_subscription = UserSubscription.objects.create(
            user=user,
            subscription_id=subscription_id,
            start_date=start_date,
            end_date=end_date
        )

        payment = paypalrestsdk.Payment({
            "intent": "sale",
            "payer": {
                "payment_method": "paypal"
            },
            "redirect_urls": {
                "return_url": reverse('subscription:execute_payment'),
                "cancel_url": reverse('subscription:cancel_payment')
            },
            "transactions": [{
                "amount": {
                    "total": selected_price,
                    "currency": "USD"
                },
                "description": "Subscription Payment"
            }]
        })

        if payment.create():
            for link in payment.links:
                if link.method == "REDIRECT":
                    return redirect(link.href)
            return HttpResponse("Failed to redirect to PayPal.")
        else:
            return HttpResponse("Payment creation failed.")
    else:
        return render(request, 'subscription/checkout.html')

subscription/templates/subscription/checkout.html
{% extends 'core/main.html' %}

{% block content %}
<div class="d-flex justify-content-center align-items-center min-vh-100 bg-gray-100">
  <div class="bg-white shadow-lg rounded-lg p-4 p-md-5 mx-auto" style="max-width: 28rem;">
    <h2 class="text-center font-weight-bold mb-4">Pay with PayPal</h2>
    <div class="text-center mb-4"><i class="fa fa-dollar"></i> {{ selected_price }}</div>
    <div id="paypal-button-container" class="text-center"></div>
  </div>
</div>

<script src="https://www.paypal.com/sdk/js?client-id={{ paypal_client_id }}&vault=true"></script>
<script>
  paypal.Buttons({
    createOrder: function(data, actions) {
      let price = parseFloat('{{ selected_price }}');
      
      return actions.order.create({
        purchase_units: [{
          amount: {
            value: price.toFixed(2),
            currency_code: 'USD'
          }
        }]
      });
    },
    onApprove: function(data, actions) {
      return actions.order.capture().then(function(details) {
        alert('Transaction completed successfully!');

        fetch('/execute_payment/', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'X-CSRFToken': '{{ csrf_token }}'
          },
          body: JSON.stringify({
            payment_id: data.orderID,
            payer_id: details.payer.payer_id,
            subscription_id: '{{ subscription_id }}',
            selected_price: '{{ selected_price }}'
          })
        })
        .then(response => {
          if (response.ok) {
            console.log('Payment saved successfully');
          } else {
            console.error('Failed to save payment');
          }
        })
        .catch(error => {
          console.error('Error saving payment:', error);
        });
      });
    },
    onError: function(err) {
      alert('Error occurred during payment processing. Please try again.');
    }
  }).render('#paypal-button-container');
</script>
{% endblock %}

subscription/templates/subscription/payment_failed.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Payment Failed</title>
    <!-- Add your CSS stylesheets, scripts, and necessary libraries -->
</head>
<body>
    <h1>Payment Failed</h1>
    
    <p>Sorry, we were unable to process your payment at this time. Please try again later or contact support for assistance.</p>

    <!-- Add links or buttons for users to navigate or retry payment -->

    <!-- Add any additional content, styles, or scripts -->
</body>
</html>

subscription/templates/subscription/subscription_detail.html
{% extends 'core/main.html' %}

{% block content %}
<div class="container-fluid">
  <div class="row justify-content-center align-items-center vh-100">
    <div class="col-md-6">
      <div class="card border-0 shadow-sm">
        <div class="card-body">
          <form method="POST" action="{% url 'subscription:checkout' %}" class="bg-light p-4 rounded">
            {% csrf_token %}
            <input type="hidden" name="subscription_id" value="{{ subscription.id }}">
            <input type="hidden" name="monthly_price" value="{{ monthly_price }}">
            <input type="hidden" name="semi_annual_price" value="{{ semi_annual_price }}">
            <input type="hidden" name="annual_price" value="{{ annual_price }}">
            
            <h2 class="card-title text-center text-primary mb-4">Choose a Subscription Plan</h2>

            <div class="mb-4">
              <div class="form-check">
                <input type="radio" id="monthly" name="selected_duration" value="monthly" class="form-check-input">
                <label for="monthly" class="cursor-pointer form-check-label">Subscribe Monthly - ${{ monthly_price }}</label>
              </div>
              <div class="form-check mt-3">
                <input type="radio" id="semi_annual" name="selected_duration" value="semi_annual" class="form-check-input">
                <label for="semi_annual" class="cursor-pointer form-check-label">Subscribe Semi-Annually - ${{ semi_annual_price }}</label>
              </div>
              <div class="form-check mt-3">
                <input type="radio" id="annual" name="selected_duration" value="annual" class="form-check-input">
                <label for="annual" class="cursor-pointer form-check-label">Subscribe Annually - ${{ annual_price }}</label>
              </div>
            </div>
            <button type="submit" class="btn btn-primary btn-block">
              Proceed to Checkout
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

subscription/templates/subscription/subscriptions_list.html
{% extends 'core/main.html' %}
{% block content %}
<h1 class="text-center mt-5 mb-4">Subscribe to Watch Movies</h1>
<div class="container">
    <div class="row justify-content-center">
        {% for subscription in subscriptions %}
        <div class="col-lg-4 col-md-6 col-sm-12 mb-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title mb-4 text-center">{{ subscription.name }}</h5>
                    <div class="text-center">
                        <span class="display-4 font-weight-bold">$</span>
                        <span class="display-1 font-weight-bold">{{ subscription.price }}</span>
                        <span class="font-weight-normal">/month</span>
                    </div>
                    <ul class="list-unstyled mt-4">
                        {% for benefit in subscription.benefits.all %}
                        <li class="d-flex align-items-center">
                            <svg class="bi bi-check-circle-fill text-warning me-3" width="1em" height="1em"
                                viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path
                                    d="M8 0a8 8 0 1 0 0 16A8 8 0 0 0 8 0zm3.73 5.97-4 4a.75.75 0 0 1-1.06 0l-2-2a.75.75 0 0 1 1.06-1.06L7 8.94l3.22-3.22a.75.75 0 0 1 1.06 1.06z" />
                            </svg>
                            <span class="text-muted">{{ benefit.name }}</span>
                        </li>
                        {% endfor %}
                    </ul>
                    <div class="text-center"> <!-- Added a div with text-center class -->
                        <a href="{% url 'subscription:subscription_detail' subscription.pk %}"
                            class="btn btn-primary btn-block mt-4">
                            Choose plan
                        </a>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}