core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path('', views.post_list, name='post-list'),
    path('create/', views.post_create, name='post-create'),
    path('<slug:slug>/', views.post_detail, name='post-detail'),
    path('<slug:slug>/update/', views.post_update, name='post-update'),
    path('<slug:slug>/delete/', views.post_delete, name='post-delete'),
    path('user/<str:username>/', views.user_post_list, name='user-post-list'),
    path('topic/<str:link>/', views.topic, name='topic'),
    path('search/', views.search, name='search'),
    path('profile/<str:username>/', views.public_profile, name='public-profile'),
    path('rate/<slug:slug>/<int:rating>/', views.rate_post_view, name='rate-post'),
    path('comment/<slug:slug>/', views.comment, name='comment'),
    path('contact/', views.contact_create, name='contact-create'),
    path('search-list/', views.post_search_list, name='search-list'),
]

jobs/urls.py
from django.urls import path
from . import views

app_name = "jobs"

urlpatterns = [
    path('', views.job_list, name='job_list'),
    path('job/create/', views.job_create, name='job_create'),
    path('job/<int:job_id>/', views.job_detail, name='job_detail'),
    path('job/<int:job_id>/update/', views.job_update, name='job_update'),
    path('job/<int:job_id>/delete/', views.job_delete, name='job_delete'),
    path('job/<int:job_id>/submit_bid/', views.submit_bid, name='submit_bid'),
]

subscription/urls.py
from django.urls import path
from . import views

app_name = "subscription"

urlpatterns = [
    path('subscriptions/', views.subscriptions_list, name='subscriptions_list'),
    path('subscription/<int:pk>/', views.subscription_detail, name='subscription_detail'),
    path('checkout/', views.checkout, name='checkout'),
    path('execute_payment/', views.execute_payment, name='execute_payment'),
    path('cancel_payment/', views.cancel_payment, name='cancel_payment'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('profile/<str:username>/', views.profile_view, name='profile'),
    path('profile/<str:username>/edit/', views.profile_edit_view, name='profile_edit'),
]

work_hub/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import notifications.urls

from django.views.generic.base import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    path('messages/', include('directmessages.urls')),
    path('subscription/', include('subscription.urls')),
    path('blogs/', include('core.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('sitemap_manager.urls')),
    path('jobs/', include('jobs.urls')),
    path('account/', include('users.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('social-auth/', include('social_django.urls', namespace="social")),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),name='password_reset_confirm'),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),name='password_reset_complete'),
    path(
        "robots.txt",
        TemplateView.as_view(template_name="core/robots.txt", content_type="text/plain"),
    ),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/forms.py
from django import forms
from ckeditor.widgets import CKEditorWidget
from .models import Topic, Post, PostReview, PostComment, Contact

class TopicForm(forms.ModelForm):
    """Form for creating or updating a Topic instance."""
    class Meta:
        model = Topic
        fields = ['name']

class PostForm(forms.ModelForm):
    """Form for creating or updating a Post instance."""
    main_description = forms.CharField(widget=CKEditorWidget())
    class Meta:
        model = Post
        fields = ['title', 'short_description', 'main_content', 'topics']

class ReviewForm(forms.ModelForm):
    """Form for creating or updating a PostReview instance."""
    class Meta:
        model = PostReview
        fields = ['post', 'user', 'rating']

class CommentForm(forms.ModelForm):
    """Form for creating or updating a Comment instance."""
    class Meta:
        model = PostComment
        fields = ['post', 'user', 'text']

class ContactForm(forms.ModelForm):
    """Form for creating or updating a Contact instance."""
    class Meta:
        model = Contact
        fields = ['name', 'email', 'message']

core/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import (
    HttpResponseRedirect, HttpResponseForbidden, JsonResponse, Http404
)
from django.contrib.auth.models import User
from django.urls import reverse
from django.contrib import messages
from django.db.models import Q
from functools import reduce
import operator
from subscription.models import UserSubscription
from .models import Post, PostComment, PostReview, Contact
from .forms import CommentForm, PostForm, ContactForm
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import datetime


def post_list(request):
    """
    View for listing all posts.

    Retrieves all posts and renders them in the 'blogs.html' template.

    Args:
    - request: HTTP request object.

    Returns:
    - Rendered response displaying all posts.
    """
    posts = Post.objects.order_by('-last_rating')
    posts_per_page = 10

    paginator = Paginator(posts, posts_per_page)
    page_number = request.GET.get('page')

    try:
        paginated_posts = paginator.page(page_number)
    except PageNotAnInteger:
        paginated_posts = paginator.page(1)
    except EmptyPage:
        paginated_posts = paginator.page(paginator.num_pages)

    context = {'posts': paginated_posts}
    return render(request, 'core/blogs.html', context)


def user_post_list(request, username):
    """
    View for listing posts by a specific user.

    Retrieves posts by a specific user and renders them in the 'user_posts.html' template.

    Args:
    - request: HTTP request object.
    - username: Username of the user whose posts are being fetched.

    Returns:
    - Rendered response displaying posts by the specified user.
    """
    user = get_object_or_404(User, username=username)
    posts = Post.objects.filter(author=user).order_by('-date_posted')
    context = {'posts': posts}
    return render(request, 'core/user_posts.html', context)


def post_detail(request, slug):
    """
    View for displaying details of a specific post.

    Retrieves the details of a specific post and renders them in the 'post_detail.html' template.

    Args:
    - request: HTTP request object.
    - slug: Unique identifier of the post.

    Returns:
    - Rendered response displaying details of the specified post.
    """
    post = get_object_or_404(Post, slug=slug)
    comments = PostComment.objects.filter(post=post).order_by('-id')
    form = CommentForm(request.POST or None)
    topics = post.topics.all()
    
    if post.subscription_required:
        user_subscription = UserSubscription.objects.filter(user=request.user).first()
        if not user_subscription or user_subscription.end_date < datetime.date.today():
            return redirect('subscription:subscriptions_list')
    
    if request.method == 'POST' and form.is_valid():
        text = form.cleaned_data['text']
        new_comment = PostComment(text=text, post=post, user=request.user)
        new_comment.save()
        messages.success(request, "Your comment has been added. Thank you")
        return HttpResponseRedirect(reverse('post-detail', kwargs={'slug': slug}))
    context = {
        'post': post,
        'comments': comments,
        'form': form,
        'topics': topics,
        }
    return render(request, 'core/post_detail.html', context)


@login_required
def post_create(request):
    """
    View for creating a new post.

    Allows authenticated users to create new posts.

    Args:
    - request: HTTP request object.

    Returns:
    - Redirects to the newly created post's detail page.
    """
    if request.user.userplan.plan.plan_type in ["Unlimited", "Standard"] or request.user.is_superuser:
        form = PostForm(request.POST or None)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return HttpResponseRedirect(reverse('post-detail', kwargs={'slug': post.slug}))
        
        context = {'form': form}
        return render(request, 'core/post_form.html', context)
    else:
        return HttpResponseRedirect(reverse('plan'))


@login_required
def post_update(request, slug):
    """
    View for updating an existing post.

    Allows authenticated users to update their own posts.

    Args:
    - request: HTTP request object.
    - slug: Unique identifier of the post to be updated.

    Returns:
    - Redirects to the updated post's detail page.
    """
    post = get_object_or_404(Post, slug=slug)
    if request.user != post.author:
        raise PermissionDenied
    
    form = PostForm(request.POST or None, instance=post)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('post-detail', kwargs={'slug': slug}))
    
    context = {'form': form}
    return render(request, 'core/post_form.html', context)


@login_required
def post_delete(request, slug):
    """
    View for deleting a post.

    Allows authenticated users to delete their own posts.

    Args:
    - request: HTTP request object.
    - slug: Unique identifier of the post to be deleted.

    Returns:
    - Redirects to the home page after deleting the post.
    """
    post = get_object_or_404(Post, slug=slug)
    if request.user != post.author:
        raise PermissionDenied
    
    post.delete()
    return HttpResponseRedirect('/')


def topic(request, link):
    """
    View for displaying posts based on topic.

    Retrieves posts based on the provided topic and renders them in the 'blogs.html' template.

    Args:
    - request: HTTP request object.
    - link: topic identifier.

    Returns:
    - Rendered response displaying posts of the specified topic.
    """
    topics = {
        "graphics-design": "Graphics & Design",
        # ... (other topic mappings)
    }
    try:
        posts = Post.objects.filter(topic=topics.get(link))
        return render(request, 'core/blogs.html', {'posts': posts})
    except KeyError:
        return redirect('home')


def search(request):
    """
    View for searching posts by title.

    Retrieves posts based on the provided title query and renders them in the 'post_search_results.html' template.

    Args:
    - request: HTTP request object.

    Returns:
    - Rendered response displaying search results.
    """
    query = request.GET.get('title')
    if query:
        posts = Post.objects.filter(title__icontains=query)
        context = {'posts': posts}
        return render(request, 'core/post_search_results.html', context)
    else:
        return redirect('home')


@login_required
def public_profile(request, username):
    """
    View for displaying the public profile of a user.

    Retrieves the public profile information and posts of the specified user and renders them in the 'public_profile.html' template.

    Args:
    - request: HTTP request object.
    - username: Username of the user whose profile is being viewed.

    Returns:
    - Rendered response displaying the public profile of the specified user.
    """
    obj = get_object_or_404(User, username=username)
    posts = Post.objects.filter(author__username=obj).order_by('-date_posted')
    context = {'posts': posts, 'username': obj}
    return render(request, 'core/public_profile.html', context)


@login_required
def rate_post_view(request, slug, rating):
    """
    View for rating a post.

    Allows authenticated users to rate a post.

    Args:
    - request: HTTP request object.
    - slug: Unique identifier of the post to be rated.
    - rating: Rating value given by the user.

    Returns:
    - Redirects to the post's detail page after rating.
    """
    try:
        post = Post.objects.get(slug=slug)
        if post and not PostReview.objects.filter(user=request.user, post=post).exists():
            review = PostReview(post=post, user=request.user, rating=rating)
            review.save()
            post.last_rating = post.calc_rating
            post.save()
            messages.success(request, f'You rated a post: {post.title}')
        else:
            messages.warning(request, f'You already rated this post')
        return redirect('post-detail', slug=post.slug)
    except Post.DoesNotExist:
        raise Http404("Post is unavailable")


@login_required
def comment(request, slug):
    """
    View for commenting on a post.

    Allows authenticated users to comment on a post.

    Args:
    - request: HTTP request object.
    - slug: Unique identifier of the post to comment on.

    Returns:
    - Redirects to the post's detail page after commenting.
    """
    return redirect('post-detail', slug=slug)


def contact_create(request):
    """
    View for creating a contact message.

    Allows users to send contact messages.

    Args:
    - request: HTTP request object.

    Returns:
    - Redirects to the home page after sending the contact message.
    """
    form = ContactForm(request.POST or None)
    if form.is_valid():
        contact = form.save(commit=False)
        contact.author = request.user
        contact.save()
        return HttpResponseRedirect(reverse('home'))
    
    context = {'form': form}
    return render(request, 'core/contact_form.html', context)


def post_search_list(request):
    """
    View for searching posts.

    Retrieves posts based on the provided search query and renders them in the 'blogs.html' template.

    Args:
    - request: HTTP request object.

    Returns:
    - Rendered response displaying search results.
    """

core/templates/core/blogs.html
{% extends "core/main.html" %}
{% load humanize %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %} Available Posts {% endblock title %}

{% block content %}
<div class="container my-5">
  <div class="row">
    {% for p in posts %}
    <div class="col-lg-6 mb-4">
      <div class="card h-100">
        <div class="card-body">
          <h5 class="card-title">{{ p.title }}</h5>
          <p class="card-text">{{ p.short_description }}</p>
        </div>
        <div class="card-footer">
          <a href="{% url 'core:post-detail' p.slug %}"
            class="btn btn-primary btn-sm">
            See More <i class="fas fa-arrow-right ml-1"></i>
          </a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  <!-- Pagination links -->
  <div class="d-flex justify-content-center mt-4">
    <ul class="pagination">
      {% if posts.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page=1">&laquo; First</a>
      </li>
      <li class="page-item">
        <a class="page-link"
          href="?page={{ posts.previous_page_number }}">Previous</a>
      </li>
      {% endif %}

      {% for num in posts.paginator.page_range %}
      <li class="page-item {% if num == posts.number %}active{% endif %}">
        <a class="page-link" href="?page={{ num }}">{{ num }}</a>
      </li>
      {% endfor %}

      {% if posts.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ posts.next_page_number }}">Next</a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ posts.paginator.num_pages }}">Last
          &raquo;</a>
      </li>
      {% endif %}
    </ul>
  </div>
</div>
{% endblock %}

core/templates/core/contact_form.html
{% extends "core/main.html" %} {% load static %}{% load crispy_forms_tags %}{% block title %}Contact{%endblock title%}{% block content %}
<div class="pt-5"></div>
<div class="container pt-5">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4" style="font-weight: bold;">Contact</legend>
            {{ form.media }} {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-murste" type="submit">Send</button>
        </div>
    </form>
</div>
{% endblock content %}

core/templates/core/home.html
{% extends "core/main.html" %}
{% load static %}
{% load humanize %}

{% block content %}
<section class="jumbotron jumbotron-fluid text-white text-center bg-dark py-5 mb-0">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 mx-auto">
        <h1 class="display-4 fw-bold">Find Your Next Opportunity</h1>
        <p class="lead mb-4">JobSpeedyUp is a powerful web application that provides a convenient platform for job seekers and employers to connect and exchange opportunities.</p>
        <a href="{% url 'jobs:job_list' %}" class="btn btn-info btn-lg">Browse Jobs</a>
      </div>
    </div>
  </div>
</section>

  <!-- Features Section -->
  <section class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <div class="card mb-4">
            <div class="card-body">
              <h3 class="card-title">Post Jobs</h3>
              <p class="card-text">Employers can post job opportunities and receive applications from qualified candidates, making it easy to find the best talent for their company.</p>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card mb-4">
            <div class="card-body">
              <h3 class="card-title">Browse Jobs</h3>
              <p class="card-text">Job seekers can browse through a wide range of job opportunities posted by various employers and apply for jobs that match their skills and interests.</p>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card mb-4">
            <div class="card-body">
              <h3 class="card-title">Post Projects and Blogs</h3>
              <p class="card-text">The platform also allows users to post their projects and blogs for a fee, as detailed in the pricing page. With JobSpeedyUp, users can showcase their skills and creativity by posting their own projects and blogs. Our payment system is integrated to allow for easy and secure payments when users are posting their projects or blogs.</p>
              <a href="{% url 'subscription:subscriptions_list' %}" class="btn btn-info">View Pricing</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- Services Section -->
  <section id="services" class="services section-bg">
    <div class="container">
      <div class="section-title">
        <h2>Our Services</h2>
        <p>JobSpeedyUp offers a wide range of services for job seekers and employers</p>
      </div>

      <div class="row">
        <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0">
          <div class="icon-box">
            <div class="icon"><i class="bi bi-briefcase"></i></div>
            <h4 class="title"><a href="">Job Postings</a></h4>
            <p class="description">Employers can post job opportunities and receive applications from qualified candidates.</p>
          </div>
        </div>

        <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0">
          <div class="icon-box">
            <div class="icon"><i class="bi bi-laptop"></i></div>
            <h4 class="title"><a href="">Post Projects and Blogs</a></h4>
            <p class="description">Users can post their projects and blogs for a fee, as detailed in the pricing page.</p>
          </div>
        </div>

        <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0">
          <div class="icon-box">
            <div class="icon"><i class="bi bi-people"></i></div>
            <h4 class="title"><a href="">Talent Search</a></h4>
            <p class="description">Job seekers can browse through a wide range of job opportunities posted by various employers and apply for jobs that match their skills and interests.</p>
          </div>
        </div>

        <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0">
          <div class="icon-box">
            <div class="icon"><i class="bi bi-wallet2"></i></div>
            <h4 class="title"><a href="">Secure Payments</a></h4>
            <p class="description">Our payment system is integrated to allow for easy and secure payments when users are posting their projects or blogs.</p>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- Call To Action Section -->
  <section id="cta" class="cta">
    <div class="container">
      <div class="row">
        <div class="col-lg-9 text-center text-lg-start">
          <h3>Start your journey with us now</h3>
          <p>Join the JobSpeedyUp community and start exploring a world of opportunities.</p>
        </div>
        <div class="col-lg-3 cta-btn-container text-center">
          <a class="cta-btn btn btn-primary btn-lg align-middle" href="{% url 'users:register' %}">Join Now</a>
        </div>
      </div>
    </div>
  </section>
  <script>
    // Animate the banner elements on page load
    document.addEventListener("DOMContentLoaded", function() {
      const banner = document.querySelector('.jumbotron');
      banner.classList.add('fade-in-up');
    });
  </script>
{% endblock content %}

core/templates/core/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title> Jobspeedyup:{% block title %} {% endblock title %}</title>
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content name="keywords">
        <meta content name="description">
        <!-- Favicons -->
        <link href="{% static 'images/logo/favicon.png' %}" rel="icon">
        <!-- Google Fonts -->
        <link
            href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Montserrat:300,400,500,700"
            rel="stylesheet">
        <link
            href="https://fonts.googleapis.com/css2?family=Mukta:wght@700&display=swap"
            rel="stylesheet">
        <link
            href="https://fonts.googleapis.com/css2?family=EB+Garamond&display=swap"
            rel="stylesheet">
        <!-- Bootstrap CSS File -->
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
            crossorigin="anonymous">
        <link rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <!-- Main Stylesheet File -->
        <link type="text/css" href="{% static 'css/style.css' %}"
            rel="stylesheet">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light px-5 shadow">
            <a class="navbar-brand ms-3" href="{% url 'home' %}"><img
                    src="{% static 'images/logo/logo.png' %}" width="160"
                    height="17" alt="logo" /></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarNav" aria-controls="navbarNav"
                aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-2">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'jobs:job_list' %}">Browse Jobs <span
                                class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link"
                            href="{% url 'core:post-list' %}">Blogs</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link"
                            href="{% url 'subscription:subscriptions_list' %}">Pricing</a>
                    </li>
                </ul>
                <ul class="navbar-nav ms-auto d-flex justify-content-end">
                    {% if user.is_authenticated %}
                    {% if user.is_superuser %}
                    <li class="nav-item me-2">
                        <a class="nav-link"
                            href="{% url 'admin:index' %}">Admin</a>
                    </li>
                    {%endif%}
                    <li class="nav-item nav-button me-2">
                        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item nav-button me-2">
                        <a class="nav-link" href="{% url 'login' %}">Login</a>
                    </li>
                    <li class="nav-item nav-button">
                        <a class="nav-link btn btn-sm btn-outline-info br-5"
                            href="{% url 'users:register' %}">Get started
                            now</a>
                    </li>
                    {% endif %}
                </ul>
                {% if user.is_authenticated %}
                <div class="dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button"
                        id="profile-dropdown" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        <img class="rounded-circle"
                            src="{% static 'images/profile_pics/beu.jpg' %}"
                            width="30" height="30" alt="Profile Image">
                    </a>

                    <ul class="dropdown-menu dropdown-menu-end"
                        aria-labelledby="profile-dropdown">
                        <li>
                            <a class="dropdown-item"
                                href="{% url 'users:profile' username=request.user.username %}">Profile</a>
                        </li>
                        <li>
                            <a class="dropdown-item"
                                href="{% url 'logout' %}">Logout</a>
                        </li>
                    </ul>
                </div>
                {% endif %}

                <!-- Toggle button for small devices -->
                <button class="navbar-toggler d-lg-none" type="button"
                    data-toggle="collapse" data-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false"
                    aria-label="Toggle navigation" id="toggle-btn">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
        <div class>
            {% block content %} {% endblock %}
        </div>
        <!-- Footer -->
        <footer class="mt-4">
            <div class="container text-center">
            <div class="social-icons">
                <!-- Font Awesome Icons -->
                <a href="#" target="_blank"><i class="fab fa-facebook-f"></i></a>
                <a href="#" target="_blank"><i class="fab fa-twitter"></i></a>
                <a href="#" target="_blank"><i class="fab fa-instagram"></i></a>
                <a href="#" target="_blank"><i class="fab fa-linkedin-in"></i></a>
            </div>
            <p class="footer-text">&copy; 2024 YourWebsite.com | Created by <a href="#" target="_blank">Your Name</a></p>
            </div>
        </footer>
        <script>
        // Toggle sidebar when the toggle button is clicked
        document.getElementById("toggle-btn").addEventListener("click", function() {
            document.getElementById("sidebar").style.width = "250px";
        });

        // Close sidebar when the close button is clicked
        document.getElementById("close-btn").addEventListener("click", function() {
            document.getElementById("sidebar").style.width = "0";
        });
    </script>
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
        <script src="https://kit.fontawesome.com/f102f3c63c.js"
            crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <script
            src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>

        <script src="{ static 'js/main.js' }"
            </body>
</html>

core/templates/core/post_confirm_delete.html
{% extends "core/main.html" %} {% block title %}Confirm delete{% endblock %} {% block header %}{%endblock header%}{% block content %}
<div class="pt-5"></div>
<div class="container pt-5" style="font-family: 'Mukta', sans-serif!important;">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Delete Post</legend>
            <h2>Are you sure you want to delete the post "{{ object.title }}"</h2>
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
            <a class="btn btn-outline-secondary" href="{% url 'core:post-detail' object.id %}">Cancel</a>
        </div>
    </form>
</div>
{% endblock content %}