core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path('', views.post_list, name='post-list'),
    path('create/', views.post_create, name='post-create'),
    path('<slug:slug>/', views.post_detail, name='post-detail'),
    path('<slug:slug>/update/', views.post_update, name='post-update'),
    path('<slug:slug>/delete/', views.post_delete, name='post-delete'),
    path('user/<str:username>/', views.user_post_list, name='user-post-list'),
    path('topic/<str:link>/', views.topic, name='topic'),
    path('search/', views.search, name='search'),
    path('profile/<str:username>/', views.public_profile, name='public-profile'),
    path('rate/<slug:slug>/<int:rating>/', views.rate_post_view, name='rate-post'),
    path('comment/<slug:slug>/', views.comment, name='comment'),
    path('contact/', views.contact_create, name='contact-create'),
    path('search-list/', views.post_search_list, name='search-list'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('profile/<str:username>/', views.profile_view, name='profile'),
    path('profile/<str:username>/edit/', views.profile_edit_view, name='profile_edit'),
]

work_hub/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import notifications.urls

from django.views.generic.base import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    path('messages/', include('directmessages.urls')),
    path('subscription/', include('subscription.urls')),
    path('blogs/', include('core.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('sitemap_manager.urls')),
    path('jobs/', include('jobs.urls')),
    path('account/', include('users.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('social-auth/', include('social_django.urls', namespace="social")),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),name='password_reset_confirm'),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),name='password_reset_complete'),
    path(
        "robots.txt",
        TemplateView.as_view(template_name="core/robots.txt", content_type="text/plain"),
    ),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from PIL import Image
from io import BytesIO
from django.core.files.base import ContentFile

class Profile(models.Model):
    """Model representing a user profile."""
    JOB_CHOICES = [
        ('open', 'Open to Work'),
        ('employed', 'Employed'),
        ('student', 'Student'),
        ('freelance', 'Freelance'),
        ('unemployed', 'Unemployed'),
    ]

    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    bio = models.TextField()
    profile_image = models.ImageField(upload_to='profile_images/', default="profile_images/default.jpg")
    job_status = models.CharField(max_length=20, choices=JOB_CHOICES, null=True, blank=True)
    
    def save(self, *args, **kwargs):
        """
        Override the save method to
        define the image aspect ratio
        """
        if self.profile_image:
            img = Image.open(self.profile_image)
            output = BytesIO()

            # Define the aspect ratio (1:1)
            target_width = target_height = 300

            img.thumbnail((target_width, target_height))

            # Save the resized image to the BytesIO object
            img.save(output, format='JPEG', quality=75)
            output.seek(0)

            # Set the image content to the associated ImageField
            self.profile_image.file = ContentFile(output.getvalue())

        super().save(*args, **kwargs)

    def __str__(self):
        """String representation of the profile."""
        return f"Profile of {self.user.username}"

    class Meta:
        verbose_name = 'Profile'
        verbose_name_plural = 'Profiles'

    class Meta:
        verbose_name = 'Profile'
        verbose_name_plural = 'Profiles'

class Experience(models.Model):
    """Model representing work experience."""
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    company = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        """String representation of the experience."""
        return f"{self.title} at {self.company}"

    class Meta:
        verbose_name = 'Experience'
        verbose_name_plural = 'Experiences'
        ordering = ['-start_date']

class Education(models.Model):
    """Model representing education details."""
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    degree = models.CharField(max_length=100)
    institution = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)

    def __str__(self):
        """String representation of the education."""
        return f"{self.degree} at {self.institution}"

    class Meta:
        verbose_name = 'Education'
        verbose_name_plural = 'Educations'
        ordering = ['-start_date']

class Contact(models.Model):
    """Model representing contact information."""
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    address = models.CharField(max_length=100, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    linkedin = models.URLField(null=True, blank=True)
    twitter = models.URLField(null=True, blank=True)

    def __str__(self):
        """String representation of the contact."""
        return f"Contact for {self.profile.user.username}"

    class Meta:
        verbose_name = 'Contact'
        verbose_name_plural = 'Contacts'

users/forms.py
from django import forms
from .models import Experience, Education, Contact, Profile

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['profile_image', 'job_status']
class ExperienceForm(forms.ModelForm):
    class Meta:
        model = Experience
        fields = ['title', 'company', 'location', 'start_date', 'end_date', 'description']

class EducationForm(forms.ModelForm):
    class Meta:
        model = Education
        fields = ['degree', 'institution', 'location', 'start_date', 'end_date']

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['address', 'email', 'linkedin', 'twitter']

users/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile, Experience, Education, Contact
from .forms import ExperienceForm, EducationForm, ContactForm, ProfileForm

def register_view(request):
    """
    View for user registration.
    Uses Django's built-in UserCreationForm.
    """
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')
    else:
        form = UserCreationForm()
    
    return render(request, 'users/register.html', {'form': form})


def profile_view(request, username):
    """
    Display user profile, experiences, education, and contact details.

    Renders the user's profile page showing their details, experiences, education,
    and contact information based on the provided username. If the user doesn’t exist,
    returns a 404 error.
    """
    user_profile = get_object_or_404(Profile, user__username=username)
    experiences = Experience.objects.filter(profile=user_profile).order_by('-start_date')
    educations = Education.objects.filter(profile=user_profile).order_by('-start_date')
    contact_info = Contact.objects.select_related('profile').filter(profile=user_profile).first()
    
    context = {
            'user_profile': user_profile,
            'experiences': experiences,
            'educations': educations,
            'contact_info': contact_info,
    }
    
    is_own_profile = False
    if request.user.is_authenticated and request.user == user_profile.user:
        is_own_profile = True
        return render(request, 'users/profile.html', context)
    return render(request, 'users/public_profile.html', context)

@login_required
def profile_edit_view(request, username):
    """
    Edit user profile, experiences, education, and contact details.

    GET:
    Renders forms to edit user details.

    POST:
    Updates profile, experiences, education, and contact details if valid;
    Redirects to the user's profile page on success, re-renders the edit
    page with errors if forms are invalid.
    """
    user_profile = get_object_or_404(Profile, user__username=username)
    
    if request.method == 'POST':
        profile_form = ProfileForm(data=request.POST, instance=user_profile)
        experience_form = ExperienceForm(data=request.POST)
        education_form = EducationForm(data=request.POST)
        contact_form = ContactForm(data=request.POST)

        if profile_form.is_valid() and experience_form.is_valid() and education_form.is_valid() and contact_form.is_valid():
            profile_form.save()
            experience = experience_form.save(commit=False)
            experience.profile = user_profile
            experience.save()
            education = education_form.save(commit=False)
            education.profile = user_profile
            education.save()
            contact = contact_form.save(commit=False)
            contact.profile = user_profile
            contact.save()
            return redirect('profile', username=username)
    else:
        profile_form = ProfileForm(instance=user_profile)
        experience_form = ExperienceForm()
        education_form = EducationForm()
        contact_form = ContactForm()

    context = {
        'user_profile': user_profile,
        'profile_form': profile_form,
        'experience_form': experience_form,
        'education_form': education_form,
        'contact_form': contact_form,
    }

    return render(request, 'users/profile_edit.html', context)

users/templates/users/login.html
{% extends 'core/main.html' %} {% load static %} {% block title %}Login{% endblock %} {% block header %}{%endblock header%}{% block content %} {% load crispy_forms_tags %}
<div class="container">
    <div class="container text-center pt-5">
        {% if messages %}
          {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
              {{ message }}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
          {% endfor %}
        {% endif %}
      
        {% if form.non_field_errors %}
          <div class="alert alert-danger alert-dismissible fade show" role="alert">
            {% for error in form.non_field_errors %}
              {{ error }}
            {% endfor %}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        {% endif %}
      </div>
      
    <div class="container my-5">
        <div class="row justify-content-center">
          <div class="col-md-6">
            <div class="card">
              <div class="card-header">
                <h4 class="card-title text-center mb-0">Login</h4>
              </div>
              <div class="card-body">
                <form method="POST">
                    {% csrf_token %} {{ form.media }}
                  <div class="mb-3">
                    <label for="email" class="form-label">Email address</label>
                        {{ form.username.errors }}
                        <div>
                            {{form.username}}
                        </div>
                    <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
                  </div>
                  <div class="mb-3">
                    <label for="password" class="form-label">Password</label>
                        {{ form.password.errors }}
                        <div>
                            {{form.password}}
                        </div>
                  </div>
                  <div class="mb-3 form-check">
                    <input type="checkbox" class="form-check-input" id="rememberMe">
                    <label class="form-check-label" for="rememberMe">Remember me</label>
                  </div>
                  <input type="submit" class="btn btn-info w-100" value="login">
                </form>
              </div>
              <div class="card-footer">
                <a href="{% url 'password_reset' %}">Forgot password?</a>
                <a href="{% url 'users:register' %}" class="float-end">Create account</a>
              </div>
            </div>
          </div>
        </div>
      </div>
</div>
{% endblock content %}

users/templates/users/logout.html
{% extends 'core/main.html' %} {% load static %} {% block title %}Logout{% endblock %}{% block header %}{%endblock header%} {% block content %}
<div class="container container-top pt-5" style="font-family: montserrat;">
    <div class="container pt-5">

        <div class="border-top mb-5">
            <h2>You have been logged out</h2>
            <small class="text-muted">
            <a class="ml-2" href="{% url 'login' %}">Log in again</a>
        </small>
        </div>
    </div>
</div>

{% endblock content %} {% block footer %} {% endblock footer %}

users/templates/users/password_reset.html
{% extends "core/main.html" %} {% load crispy_forms_tags %} {% block title %}Password Reset{% endblock %} {% block header %}{%endblock header%}{% block content %}
<div class="pt-5"></div>
<div class="container pt-5" style="font-family: montserrat;">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Reset Password</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-murste" type="submit">Request Password Reset</button>
        </div>
    </form>
</div>
{% endblock content %}

users/templates/users/password_reset_complete.html
{% extends "core/main.html" %} {% block title %}Password reset{% endblock %} {% block header %}{%endblock header%}{% block content %}
<div class="container pt-5" style="font-family: montserrat;">
<div class="alert alert-info">
    Your password has been set.
</div>

<a href="{% url 'login' %}">Sign In Here</a> </div>{% endblock content %}

users/templates/users/profile.html
{% extends 'core/main.html' %}
{% load static %}
{% block title %}User Profile{% endblock %}
{% block content %}
<div class="container mt-5">
  <div class="row">
    <div class="col-lg-4">
      <div class="card mb-4">
        <div class="card-body text-center">
          <img src="{{user_profile.profile_image.url}}" class="img-fluid rounded-circle mb-3 profile-img" alt="Profile Image">
          {% if user_profile %}
          <h5 class="card-title">{{ user_profile.user.username }}</h5>
          <p class="text-muted">{{ user_profile.job_status }}</p>
          {% endif %}
          <div class="mt-4">
            <a href="{% url 'users:profile_edit' username=request.user.username %}" class="btn btn-primary">
              <i class="fa fa-user-edit mr-2"></i> Edit Profile
            </a>
          </div>
        </div>
      </div>
      <div class="card">
        <div class="card-body">
          {% if contact_info %}
          <h5 class="card-title">Contact Information</h5>
          <p><i class="fa fa-envelope mr-2"></i><strong> Email:</strong> {{ contact_info.email }}</p>
          <p><i class="fa fa-linkedin mr-2"></i><strong> LinkedIn:</strong> {{ contact_info.linkedin }}</p>
          <p><i class="fa fa-twitter mr-2"></i><strong> Twitter:</strong> {{ contact_info.twitter }}</p>
          {% else %}
          <p class="text-muted">No contact information available.</p>
          {% endif %}
        </div>
      </div>
    </div>

    <div class="col-lg-8">
      <div class="card mb-4">
        <div class="card-body">
          {% if user_profile %}
          <h5 class="card-title">Bio</h5>
          <p>{{ user_profile.bio | default:"No bio available" }}</p>
          {% else %}
          <p class="text-muted">No bio available.</p>
          {% endif %}
        </div>
      </div>
      <div class="card mb-4">
        <div class="card-body">
          {% if experiences %}
          <h5 class="card-title">Experiences</h5>
          <ul class="list-group">
            {% for experience in experiences %}
            <li class="list-group-item">
              <i class="fa fa-briefcase mr-2"></i><strong> {{ experience.title }}</strong> at {{ experience.company }}
            </li>
            {% endfor %}
          </ul>
          {% else %}
          <p class="text-muted">No experiences available.</p>
          {% endif %}
        </div>
      </div>
      <div class="card">
        <div class="card-body">
          {% if educations %}
          <h5 class="card-title">Education</h5>
          {% for education in educations %}
          <p><i class="fa fa-graduation-cap mr-2"></i><strong> Degree:</strong> {{ education.degree }}</p>
          <p><i class="fa fa-university mr-2"></i><strong> Institution:</strong> {{ education.institution }}</p>
          <!-- Add more education fields as needed -->
          {% endfor %}
          {% else %}
          <p class="text-muted">No education information available.</p>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

users/templates/users/profile_edit.html
{% extends 'core/main.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}Profile Edit{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-lg-8">
            <div class="card shadow">
                <div class="card-header bg-primary text-white">Edit Profile</div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="mb-3">
                            {{ profile_form|crispy }}
                        </div>
                        <div class="mb-3">
                            {{ experience_form|crispy }}
                        </div>
                        <div class="mb-3">
                            {{ education_form|crispy }}
                        </div>
                        <div class="mb-3">
                            {{ contact_form|crispy }}
                        </div>
                        <div class="row justify-content-end">
                            <div class="col-md-6">
                                <button type="submit" class="btn btn-primary btn-block">
                                    <i class="fa fa-save mr-2"></i> Save Changes
                                </button>
                            </div>
                            <div class="col-md-6 mt-2 mt-md-0">
                                <a href="{% url 'users:profile' username=user_profile.user.username %}" class="btn btn-secondary btn-block">
                                    <i class="fa fa-arrow-left mr-2"></i> Back to Profile
                                </a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

users/templates/users/public_profile.html
{% extends 'core/main.html' %}
{% load static %}
{% block title %}User Profile{% endblock %}
{% block content %}
<div class="container mt-5">
  <div class="row">
    <div class="col-lg-4">
      <div class="card mb-4">
        <div class="card-body text-center">
          <img src="{{user_profile.profile_image.url}}" class="img-fluid rounded-circle mb-3 profile-img" alt="Profile Image">
          {% if user_profile %}
          <h5 class="card-title">{{ user_profile.user.username }}</h5>
          <p class="text-muted">{{ user_profile.job_status }}</p>
          {% endif %}
        </div>
      </div>
      <div class="card">
        <div class="card-body">
          {% if contact_info %}
          <h5 class="card-title">Contact Information</h5>
          <p><i class="fa fa-envelope mr-2"></i><strong> Email:</strong> {{ contact_info.email }}</p>
          <p><i class="fa fa-linkedin mr-2"></i><strong> LinkedIn:</strong> {{ contact_info.linkedin }}</p>
          <p><i class="fa fa-twitter mr-2"></i><strong> Twitter:</strong> {{ contact_info.twitter }}</p>
          {% else %}
          <p class="text-muted">No contact information available.</p>
          {% endif %}
        </div>
      </div>
    </div>

    <div class="col-lg-8">
      <div class="card mb-4">
        <div class="card-body">
          {% if user_profile %}
          <h5 class="card-title">Bio</h5>
          <p>{{ user_profile.bio | default:"No bio available" }}</p>
          {% else %}
          <p class="text-muted">No bio available.</p>
          {% endif %}
        </div>
      </div>
      <div class="card mb-4">
        <div class="card-body">
          {% if experiences %}
          <h5 class="card-title">Experiences</h5>
          <ul class="list-group">
            {% for experience in experiences %}
            <li class="list-group-item">
              <i class="fa fa-briefcase mr-2"></i><strong> {{ experience.title }}</strong> at {{ experience.company }}
            </li>
            {% endfor %}
          </ul>
          {% else %}
          <p class="text-muted">No experiences available.</p>
          {% endif %}
        </div>
      </div>
      <div class="card">
        <div class="card-body">
          {% if educations %}
          <h5 class="card-title">Education</h5>
          {% for education in educations %}
          <p><i class="fa fa-graduation-cap mr-2"></i><strong> Degree:</strong> {{ education.degree }}</p>
          <p><i class="fa fa-university mr-2"></i><strong> Institution:</strong> {{ education.institution }}</p>
          <!-- Add more education fields as needed -->
          {% endfor %}
          {% else %}
          <p class="text-muted">No education information available.</p>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

users/templates/users/register.html
{% extends 'core/main.html' %} {% load static %} {% block title %}Login{% endblock %} {% block header %}{%endblock header%}{% block content %} {% load crispy_forms_tags %}
<div class="container">
    <div class="container text-center pt-5">
        {% if messages %}
          {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
              {{ message }}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
          {% endfor %}
        {% endif %}
      
        {% if form.non_field_errors %}
          <div class="alert alert-danger alert-dismissible fade show" role="alert">
            {% for error in form.non_field_errors %}
              {{ error }}
            {% endfor %}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        {% endif %}
      </div>
      
    <div class="container my-5">
        <div class="row justify-content-center">
          <div class="col-md-6">
            <div class="card">
              <div class="card-header">
                <h4 class="card-title text-center mb-0">Login</h4>
              </div>
              <div class="card-body">
                <form method="POST">
                    {% csrf_token %} {{ form.media }}
                  <div class="mb-3">
                    <label for="email" class="form-label">Email address</label>
                        {{ form.username.errors }}
                        <div>
                            {{form.username}}
                        </div>
                  </div>
                  <div class="mb-3">
                    <label for="email" class="form-label">Email address</label>
                        {{ form.email.errors }}
                        <div>
                            {{form.email}}
                        </div>
                    <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
                  </div>
                  <div class="mb-3">
                    <label for="password" class="form-label">Password</label>
                        {{ form.password1.errors }}
                        <div>
                            {{form.password1}}
                        </div>
                  </div>
                  <div class="mb-3">
                    <label for="password" class="form-label">Password</label>
                        {{ form.password2.errors }}
                        <div>
                            {{form.password2}}
                        </div>
                  </div>
                  <div class="mb-3 form-check">
                    <input type="checkbox" class="form-check-input" id="rememberMe">
                    <label class="form-check-label" for="rememberMe">Remember me</label>
                  </div>
                  <input type="submit" class="btn btn-info w-100" value="login">
                </form>
              </div>
              <div class="card-footer">
                <a href="{% url 'login' %}" class="float-start">Alrady have an account</a>
              </div>
            </div>
          </div>
        </div>
      </div>
</div>
{% endblock content %}

users/templates/users/user_followers.html
_{% extends "core/main.html" %} {% load material_form %} {% block content %}
<div class="container container-top">
    <div class="text-center">
        <h3>Followers</h3>
    </div>
    <hr> {% for user in profile.followers.all %}
    <div class="p-2" style="text-align: center;">
        <img class='rounded-circle article-img mt-1 crop' src="{{ user.profile.profile_image.url  }}" height="50" width="50">
        <a class="black-link" href="{% url 'public-profile' user.username %}">{{ user }}</a>
    </div>
    <hr> 
    {% endfor %} 
</div>
{% endblock %}